CREATE TABLE elections (
	ballot_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	guild_id BIGINT NOT NULL,
	candidates JSONB NOT NULL
);

CREATE TABLE ballots (
	ballot_id NOT NULL REFERENCES elections(ballot_id),
	user_id BIGINT NOT NULL,
	ranking JSONB NOT NULL,

	PRIMARY KEY (ballot_id, user_id)
);
