CREATE TABLE elections (
	election_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	creator_id BIGINT NOT NULL,
	guild_id BIGINT NOT NULL,
	title TEXT,
	candidate_names JSONB NOT NULL
);

CREATE TABLE ballots (
	election_id INTEGER NOT NULL REFERENCES elections (election_id),
	user_id BIGINT NOT NULL,
	ballot JSONB NOT NULL,

	PRIMARY KEY (election_id, user_id)
);
